# Generated by Django 5.1.1 on 2024-09-10 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='user',
        ),
        migrations.AddField(
            model_name='finance',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.visitor', verbose_name='Utilisateur'),
        ),
    ]
