# Generated by Django 5.1.1 on 2024-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_finance_user_finance_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreservation',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
