# Generated by Django 5.1.1 on 2024-09-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_bookingreservation_is_new_rating_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='property_rated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.property', verbose_name='Propriété'),
        ),
    ]
